### ISSUE TITLE
HTML Validator: spatie niet toegestaan

### ISSUE THREAD

**Issue by Annevd** [wingsvn/the-startup-responsive-interactieve-website#3]
![image](https://github.com/wingsvn/the-startup-responsive-interactieve-website/assets/144004647/f76112a2-9364-430e-8699-7461e906549e)
https://github.com/wingsvn/the-startup-responsive-interactieve-website/blob/bf76962fff3cf4357da2760af484189087e0ddb9/index.html#L13
https://github.com/wingsvn/the-startup-responsive-interactieve-website/blob/bf76962fff3cf4357da2760af484189087e0ddb9/index.html#L121

Er mogen geen spaties in de src van een img staan. Dit zou je kunnen oplossen door er streepjes tussen te zetten in plaats van spaties. Vergeet dit dan niet ook in je file naam zelf te veranderen.

Voorbeeld: 
```<img src="./Van-Ons-Assets/Mascotte/Cow.png" alt="Van Ons mascotte">```

**Comment by wingsvn** [comment]
Dankjewel, ik heb de naam van mijn file aangepast.
< img src="./VO-mascotte/Cow.png" alt="Van Ons mascotte">
