### ISSUE TITLE
HTML Validator: ```<a>``` kan niet als kind van ```<button>```

### ISSUE THREAD

**Issue by Annevd** [wingsvn/the-startup-responsive-interactieve-website#4]
![image](https://github.com/wingsvn/the-startup-responsive-interactieve-website/assets/144004647/8461f8ec-a3f6-4c88-9c6c-406524872784)

Je hebt hier een link als kind van een button.
Misschien kan je het omdraaien dat je de link om de button heen zet.

Dus:

```HTML
<a>
    <button>...</button>
</a>
```

**Comment by wingsvn** [comment]
ik heb van de link een parent gemaakt en van de button een kind. 
```
<a href="">
    <button class="button-phase">Bekijk de voortgang</button> 
</a>
